name: CI

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build and test
      run: ./build-and-test.sh --configuration ${{ matrix.configuration }}

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build and test
      run: .\build-and-test.cmd -c ${{ matrix.configuration }}
